### ISSUE TITLE
add search bar

### ISSUE THREAD

**Issue by gitlawr** [seal-io/docs#109]

**Comment by Finenyaco** [comment]
**Test Result:** pass

<img width="567" alt="image" src="https://github.com/seal-io/docs/assets/26084756/f1d56a45-5c1d-4b65-a0ff-be4ae16d7157">
<img width="557" alt="image" src="https://github.com/seal-io/docs/assets/26084756/a6be74e0-84e4-4f43-b22c-c0a8b269fab8">
