### ISSUE TITLE
Clarify the usage of templates using xxx?ref=xxx

### ISSUE THREAD

**Issue by gitlawr** [seal-io/docs#110]
We only mention tag versions in https://seal-io.github.io/docs/operation/template#template-version
Explain how to use a non-tag reference which is helpful for debugging and testing templates

**Comment by Finenyaco** [comment]
**Test Result:** pass

<img width="1157" alt="image" src="https://github.com/seal-io/docs/assets/26084756/90a74270-cc56-4bfc-b9c7-e5d885100372">

<img width="1013" alt="image" src="https://github.com/seal-io/docs/assets/26084756/543dfb94-7f82-4672-9113-41f82e091eac">
