### ISSUE TITLE
Bump version to v0.3.1

### ISSUE THREAD

**Issue by gitlawr** [seal-io/docs#112]
Replace the version placeholder in installation guides with the latest minor version

**Comment by Finenyaco** [comment]
**Test Result:** pass

<img width="983" alt="image" src="https://github.com/seal-io/docs/assets/26084756/6f90b8e7-69b7-4ac3-b006-8133400bb049">
<img width="1419" alt="image" src="https://github.com/seal-io/docs/assets/26084756/fe248852-ffef-423f-87af-3efde0362fc8">
