### ISSUE TITLE
update deployment docs

### ISSUE THREAD

**Issue by gitlawr** [seal-io/docs#163]
Airgap deployment: It should be unnecessary to configure custom deployer image now
HA deployment: Ensure the yaml manifest is updated and works

**Comment by alexcodelf** [comment]
Settings can configure Deployer network mirror URL, need docs. Hermitcrab may be mentioned.

**Comment by gitlawr** [comment]
And make sure the yaml manifest is updated and works

**Comment by thxCode** [comment]
> Settings can configure Deployer network mirror URL, need docs. Hermitcrab may be mentioned.

https://github.com/seal-io/docs/blob/main/docs/setting/setting.md#deployment

**Comment by thxCode** [comment]
closed as completed
